# Generated by Django 4.2.5 on 2023-09-29 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='No username found')),
                ('last_token', models.TextField(default='No token found')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 29, 11, 33, 7, 882547))),
            ],
        ),
    ]
