# Generated by Django 4.2.5 on 2023-09-29 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 12, 10, 2, 1356)),
        ),
    ]
