# Generated by Django 4.2.5 on 2023-09-29 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_passwordresetprofile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 13, 39, 21, 172858)),
        ),
    ]
